### PR TITLE
Cordova plugin 4.11.0

### PR DESCRIPTION
**Pull request by rutkayb**
### Version 4.11.0 (10 Aug 2021):
- 🎉 New:
  * Added `isCapturedAutomatically` in Page interface to identify whether the image was captured automatically or manually triggered by the shutter button. [Persistence of Page Objects](/04-features/02-page-model.md)
  * Added `engineMode` in BarcodeScannerConfiguration interface to specify using whether next generation barcode recognizer or the legacy one. [startBarcodeScanner](04-features/09-barcode-scanner.md#barcode-scanner)
  * Added `engineMode` in BatchBarcodeScannerConfiguration interface to specify using whether next generation barcode recognizer or the legacy one. [startBarcodeScanner](04-features/09-barcode-scanner.md#barcode-scanner)
  * Additional parameter msiPlesseyChecksumAlgorithms: MSIPlesseyChecksumAlgorithm in BarcodeScannerConfiguration to specify the checksum algorithms for MSI Plessey barcodes. [startBarcodeScanner](04-features/09-barcode-scanner.md#barcode-scanner)
  * Additional parameter msiPlesseyChecksumAlgorithms: MSIPlesseyChecksumAlgorithm in BatchBarcodeScannerConfiguration to specify the checksum algorithms for MSI Plessey barcodes. [startBarcodeScanner](04-features/09-barcode-scanner.md#barcode-scanner)
- ⚠️ Breaking Changes:
  * Renamed the parameter `enableGS1Decoding` in BarcodeScannerConfiguration as `gs1DecodingEnabled`. [startBarcodeScanner](04-features/09-barcode-scanner.md#barcode-scanner)
  * Renamed the parameter `enableGS1Decoding` in BatchBarcodeScannerConfiguration as `gs1DecodingEnabled`. [startBarcodeScanner](04-features/09-barcode-scanner.md#barcode-scanner)
  * Changed signature of the LicenseFailure interface. Added additional parameter licenseErrorMessage : String
- 🚙 Under the hood:
  * Upgraded the native Scanbot Android SDK to v1.86.0
    (cf. [changelog](/document-scanner-sdk/android/99-changelog.md))
  * Upgraded the native Scanbot iOS SDK to v1.19.3
    (cf. [changelog](/document-scanner-sdk/ios/99-changelog.md))

### CODE REVIEW

**Comment by hudson-pierce** [comment]
run tests

**Comment by rutkayb** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by rutkayb** [comment]
run tests

**Review by marcosaia1812 — APPROVED** [review]

**Comment by rutkayb** [comment]
run tests

**Pull request merged**
